### ISSUE TITLE
Tutorials missing

### ISSUE THREAD

**Issue by MarcRieraDominguez** [MPCMEvolution/MPCMArchive#1]
Hi! I am going through Chapter 8, and while the files are accessible, I can't find the tutorials. See for instance: https://www.mpcm-evolution.com/practice/online-practical-material-chapter-8/chapter-8-1-baby-delivering-storks-example
Are the tutorials accessible somewhere? Apologies in case I have overlooked them.
Best,
Marc

**Comment by Gesler16** [comment]
Hi Marc,

I had the same issue so I checked on WebArchive's Wayback Machine. The specific tutorial you are linking to seems to not be available in the archive unfortunately, but many others are (eg: https://web.archive.org/web/20200803225430/https://www.mpcm-evolution.com/practice/online-practical-material-chapter-11/chapter-11-1-simple-model-mcmcglmm). Hope this helps other people until the editors of the book come around to fix the issue on the website.

Regards,
Constantinos

**Comment by MarcRieraDominguez** [comment]
Hi Constantinos,
Thank you for the research! :)
I am happy to share a solution to the problem of lacking tutorials: right click on the tutorial you're interested in (for example, baby-delivering storks: https://www.mpcm-evolution.com/practice/online-practical-material-chapter-8), and "Save link as". You should get an html file with the tutorial.
I don't know whether this can work on all missing tutorials, but worth giving it a try.
Cheers!
Marc

**Comment by crishnakh** [comment]
Hi @MarcRieraDominguez  and @Gesler16 we are working now to keep in this repository all the materials and exercises.

**Comment by crishnakh** [comment]
Hi! I'm updating the wiki pages!

**Comment by rdiaz02** [comment]
> Hi Constantinos, Thank you for the research! :) I am happy to share a solution to the problem of lacking tutorials: right click on the tutorial you're interested in (for example, baby-delivering storks: https://www.mpcm-evolution.com/practice/online-practical-material-chapter-8), and "Save link as". You should get an html file with the tutorial. I don't know whether this can work on all missing tutorials, but worth giving it a try. Cheers! Marc

I tried that. but the file I get is just the 404 error page.

**Comment by crishnakh** [comment]
Hi

Links
> https://github.com/MPCMEvolution/MPCMArchive/blob/master/online_practical_material/online-practical-material-chapter-8.md

> https://github.com/MPCMEvolution/MPCMArchive/blob/master/online_practical_material/exercises_and_tutorials/chapter-8-1-baby-delivering-storks-example.md

> https://github.com/MPCMEvolution/MPCMArchive/blob/master/online_practical_material/exercises_and_tutorials/chapter-8-2-step-step-guide-phylogenetic-path-analysis-using-d-sep-method-rhinograds-example.md

> https://github.com/MPCMEvolution/MPCMArchive/blob/master/online_practical_material/iframe/Chapter8_OPM/Rhinograds%20example.html

> https://github.com/MPCMEvolution/MPCMArchive/blob/master/online_practical_material/iframe/Chapter8_OPM/Storks%20example.html

**Comment by rdiaz02** [comment]
Thanks! The problem is that many of those link to mpcm-evolution.com and that gives a 404. For example, if you go to the first

https://github.com/MPCMEvolution/MPCMArchive/blob/master/online_practical_material/online-practical-material-chapter-8.md

and click on either one of the first "Exercises and tutorials" , 

<img src="https://github.com/user-attachments/assets/57024748-c067-4676-a861-9ec67faea707" width=30% height=30%>


you get 404. Interestingly, the data (little bit further down) can be downloaded, but the data seem to be at mpcm-evolution.com. 


This is not a problem for the exercises and tutorials themselves, which seem available from the wiki, here: 

https://github.com/MPCMEvolution/MPCMArchive/wiki/08.-Chapter-8

However, from the wiki, the links to the data

<img src="https://github.com/user-attachments/assets/976dce08-2a90-40e5-ad98-80ad72cabb71" width=30% height=30%>

 do not work (404 again).


So I guess for now a workaround is:

1. Get the data from the links you sent (i.e., https://github.com/MPCMEvolution/MPCMArchive/tree/master/online_practical_material/data_files)
2. Get the code of the exercises and tutorials, the md, from the wiki.
